create table if not exists public.owner_app_events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  occurred_at timestamptz not null default now(),
  install_id text not null,
  session_id text not null,
  event_name text not null,
  app_version text,
  product_flavor text,
  ui_shell text,
  platform text,
  is_tauri boolean not null default false,
  details jsonb not null default '{}'::jsonb
);

create index if not exists owner_app_events_created_at_idx on public.owner_app_events (created_at desc);
create index if not exists owner_app_events_install_id_idx on public.owner_app_events (install_id);
create index if not exists owner_app_events_event_name_idx on public.owner_app_events (event_name);

create table if not exists public.owner_match_summaries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  install_id text,
  session_id text,
  app_version text,
  product_flavor text,
  ui_shell text,
  platform text,
  is_tauri boolean not null default false,
  mode text not null,
  analytics_source text,
  started_at timestamptz,
  finished_at timestamptz not null,
  players_count integer not null default 0,
  match_winner integer,
  corrections_count integer not null default 0,
  estimated_accuracy double precision,
  settings jsonb not null default '{}'::jsonb,
  players jsonb not null default '[]'::jsonb,
  match_stats jsonb not null default '[]'::jsonb
);

create index if not exists owner_match_summaries_created_at_idx on public.owner_match_summaries (created_at desc);
create index if not exists owner_match_summaries_mode_idx on public.owner_match_summaries (mode);
create index if not exists owner_match_summaries_source_idx on public.owner_match_summaries (analytics_source);

-- Run this with "Run and enable RLS".
-- Keep these tables backend-only and do not add anon/authenticated policies.
